# Generated by Django 4.0.3 on 2022-03-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_parent_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
