# Generated by Django 4.0.3 on 2022-03-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replies_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
