# Generated by Django 4.0.3 on 2022-03-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars'),
        ),
    ]
