# Generated by Django 4.0.3 on 2022-03-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
